# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: KVIB Package

on:
  push:
    branches: 
      -master
  workflow_dispatch:

jobs:
  publish:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
      contents: write

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Change directory
        run: rm -rf *
        working-directory: src/css
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x


      - run: npm ci --no-audit
#      - run: npm audit --production
#      - run: tsc
#     - run: npx npm-packlist

#      - name: Bump version and push tag
#       id: tag_version
#      uses: mathieudutour/github-tag-action@v5.3
#     with:
#          github_token: ${{ github.token }}

#      - name: Bump package.json
#        run: npm version ${{ steps.tag_version.outputs.new_version }} --no-git-tag-version

      - name: Publish library
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: 'https://npm.pkg.github.com'
          token: ${{ github.token }}
